6517 orapi release
nhs-digital-gp-it-futures/platform pull request #81
Opened 2020-04-28 09:29 UTC by roses1089

2020-04-28 14:55 UTC, stuart-bass-bjss requested changes

2020-04-28 14:55 UTC, stuart-bass-bjss commented on Kubernetes/BuyingCatalogueOrdering/test-orapi-kubernetes-manifest.yaml
> +        image: gpitfuturestestacr.azurecr.io/nhsd/buying-catalogue/orapi
image name is inconsistent with dev?

2020-04-28 15:00 UTC, stuart-bass-bjss commented on Kubernetes/BuyingCatalogueOrdering/dev-orapi-kubernetes-manifest.yml
> +      containers:
Should there be liveness / readiness probes?

2020-04-30 10:00 UTC, stuart-bass-bjss requested changes

2020-04-30 10:00 UTC, stuart-bass-bjss commented on Kubernetes/BuyingCatalogueOrdering/dev-orapi-kubernetes-manifest.yml
> +            path: /health/live
/health/ready

2020-04-30 10:00 UTC, stuart-bass-bjss commented on Kubernetes/BuyingCatalogueOrdering/test-orapi-kubernetes-manifest.yaml
> +            path: /health/live
/health/ready

2020-04-30 10:29 UTC, roses1089 commented on Kubernetes/BuyingCatalogueOrdering/test-orapi-kubernetes-manifest.yaml
> +            path: /health/live
Updated readiness Probe for Test

2020-04-30 14:07 UTC, stuart-bass-bjss approved these changes

2020-04-30 14:34 UTC, merged