Added yaml file for OrderForm
nhs-digital-gp-it-futures/platform pull request #85
Opened 2020-04-29 08:57 UTC by roses1089

Added yaml file for OrderForm for both Dev and Test

2020-04-29 14:06 UTC, stuart-bass-bjss requested changes

2020-04-29 14:06 UTC, stuart-bass-cgi commented on Kubernetes/OrderForm/dev-orderform-kubernetes-manifest.yml
> +          value: "https://buyingcataloguetestpublic.uksouth.cloudapp.azure.com"
shouldn't this be dev?

2020-04-29 14:06 UTC, stuart-bass-bjss commented on Kubernetes/OrderForm/test-orderform-kubernetes-manifest.yml
> +          value: "testelopment"
I think this variable should be removed

2020-04-29 14:06 UTC, stuart-bass-bjss commented on Kubernetes/OrderForm/dev-orderform-kubernetes-manifest.yml
> +          value: "orderform"
I think this should be /order

2020-04-30 10:24 UTC, stuart-bass-bjss requested changes

2020-04-30 10:24 UTC, stuart-bass-bjss commented on Kubernetes/OrderForm/dev-orderform-kubernetes-manifest.yml
> +          httpGet:
order form doesn't have live / ready yet

2020-04-30 14:06 UTC, stuart-bass-bjss approved these changes

2020-04-30 15:34 UTC, merged